### ISSUE TITLE
In python file, we should be able to define a base url

### ISSUE THREAD

**Issue by TAdamSmith** [766F6964/mublog#24]
In python file, we should be able to define a base url. Because everybody wont post their content on '/'. For example, me.

**Comment by 766F6964** [comment]
This is something, I have already planned. I intend to rework how paths are handled (This includes both, paths on the local system, but also paths in the generated files, aka paths that will be interpreted by the web-server).

It will be one of the next features I'll plan to work on.

**Comment by 766F6964** [comment]
@TAdamSmith After thinking about this for a bit more, I believe that defining the webroot should be the responsibility of the webserver rather than the blog generator. 
If you intend to serve the blog files from a designated directory like /var/www/html/mydirectory/, it is best to configure the webserver accordingly and set that directory as the webroot.

I don't see a good enough reason to specify a baseurl manually. But maybe you can convince me otherwise.

**Comment by 766F6964** [comment]
Closing this for now.
