### ISSUE TITLE
Rewrite project in python

### ISSUE THREAD

**Issue by 766F6964** [766F6964/mublog#6]
**Summary:**
Originally, I developed this project in shell script with the intention to have it just work everywhere, without any major dependencies.
However, this has a couple of problems:

1. The code because harder to maintain, with additional features.
2. We already have a hard dependency with _pandoc_, so the no-dependency argument doesn't really hold.
3. Writing this in python will save a lot of development time.
4. The code becomes more portable

After reading the code-review by [KubaO](https://github.com/kubao/mublog-py), I decided it is a good idea.
Work on a proper python implementation has started, and will be published over the coming days.

**Comment by KubaO** [comment]
Don't make it too "proper" though :) There's some beauty in the thing being short. Perhaps a self-imposed limitation in this project should be to keep it "short" - say "quite a bit shorter than 1000 lines in a single source, excluding the markdown module"? I like the "quite a bit shorter than" qualification, because if anyone would be fighting to squeeze lines in while keeping the total at exactly 1000, the purpose of the thing has been missed already.

**Comment by 766F6964** [comment]
Completed with https://github.com/766F6964/mublog/pull/7
